# Generated by Django 4.2.2 on 2023-10-26 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubs', '0013_noticias_usuario'),
        ('usuarios', '0007_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosFunc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50, verbose_name='O cargo do funcionário na UBS: ')),
                ('foto', models.ImageField(upload_to='fotos_funcionarios', verbose_name='foto de perfil: ')),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.ubs', verbose_name='UBS em que trabalha: ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
