# Generated by Django 4.2.2 on 2023-10-26 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubs', '0013_noticias_usuario'),
        ('usuarios', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosfunc',
            name='cargo',
            field=models.CharField(max_length=50, null=True, verbose_name='O cargo do funcionário na UBS: '),
        ),
        migrations.AlterField(
            model_name='dadosfunc',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos_funcionarios', verbose_name='foto de perfil: '),
        ),
        migrations.AlterField(
            model_name='dadosfunc',
            name='ubs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ubs.ubs', verbose_name='UBS em que trabalha: '),
        ),
        migrations.AlterField(
            model_name='dadosfunc',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
