# Generated by Django 4.2.2 on 2023-10-26 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0009_alter_dadosfunc_cargo_alter_dadosfunc_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosfunc',
            name='cargo',
            field=models.CharField(max_length=50, null=True, verbose_name='Seu cargo: '),
        ),
        migrations.AlterField(
            model_name='dadosfunc',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
