# Generated by Django 4.2.2 on 2024-01-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
