# Generated by Django 4.2.2 on 2024-01-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_duvida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duvida',
            name='resposta',
            field=models.ManyToManyField(null=True, to='usuarios.respostas'),
        ),
    ]
