# Generated by Django 4.2.2 on 2024-01-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_duvida_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='duvida',
            name='duvida',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
