# Generated by Django 4.2.2 on 2024-01-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_duvida_duvida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duvida',
            name='resposta',
        ),
        migrations.AddField(
            model_name='respostas',
            name='duvida',
            field=models.ManyToManyField(null=True, to='usuarios.duvida'),
        ),
    ]
