# Generated by Django 4.2.2 on 2024-01-07 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_alter_duvida_criadoin_alter_respostas_criado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostas',
            name='duvida',
        ),
        migrations.AddField(
            model_name='respostas',
            name='duvida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.duvida'),
        ),
    ]
