# Generated by Django 4.2.2 on 2024-01-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_remove_respostas_duvida_respostas_duvida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duvida',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_respostas'),
        ),
    ]
