# Generated by Django 4.2.3 on 2023-09-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveIntegerField(verbose_name='Dias da semana de atendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=500, verbose_name='Serviço: ')),
            ],
        ),
        migrations.CreateModel(
            name='Ubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome: ')),
                ('bairro', models.CharField(max_length=150, verbose_name='Bairro: ')),
                ('rua', models.CharField(max_length=150, verbose_name='Rua: ')),
                ('numero', models.PositiveIntegerField(verbose_name='Número: ')),
                ('cep', models.CharField(max_length=8, verbose_name='Cep: ')),
                ('referencia', models.CharField(max_length=120, verbose_name='Ponto de Referência: ')),
                ('data_fundacao', models.DateField(verbose_name='Data de fundação: ')),
                ('foto', models.ImageField(upload_to='fotos_ubs', verbose_name='Imagem da UBS: ')),
                ('horario_de_inicio', models.PositiveIntegerField(verbose_name='Horário de início de atendimento')),
                ('horario_de_termino', models.PositiveIntegerField(verbose_name='Horário de término de atendimento')),
                ('cadastro_servico', models.ManyToManyField(to='ubs.servicos')),
                ('dia', models.ManyToManyField(to='ubs.diasemana')),
            ],
        ),
    ]
