# Generated by Django 4.2.2 on 2023-09-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diasemana',
            name='dia',
            field=models.CharField(max_length=20, verbose_name='Dias da semana de atendimento'),
        ),
    ]
