# Generated by Django 4.2.2 on 2023-09-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubs', '0003_bairro_alter_ubs_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubs',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='Cep: '),
        ),
    ]
