# Generated by Django 4.2.2 on 2023-09-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubs', '0005_alter_ubs_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='descricao',
            field=models.CharField(default=1, max_length=500, verbose_name='Descrição do serviço: '),
            preserve_default=False,
        ),
    ]
