# Generated by Django 4.2.2 on 2023-09-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubs', '0006_servicos_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubs',
            name='dia',
            field=models.ManyToManyField(to='ubs.diasemana', verbose_name='Dias de funcionamento: '),
        ),
    ]
