# Generated by Django 4.2.2 on 2023-10-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubs', '0007_alter_ubs_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubs',
            name='horario_de_inicio',
            field=models.TimeField(verbose_name='Horário de início de atendimento'),
        ),
        migrations.AlterField(
            model_name='ubs',
            name='horario_de_termino',
            field=models.TimeField(verbose_name='Horário de término de atendimento'),
        ),
    ]
