# Generated by Django 4.2.2 on 2023-10-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubs', '0008_alter_ubs_horario_de_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da notícia')),
                ('body', models.CharField(max_length=1000, verbose_name='Noticia')),
                ('imagem', models.ImageField(upload_to='fotos_noticias', verbose_name='Foto ilustrativa da noticia')),
                ('ubs_relacionada', models.ManyToManyField(to='ubs.ubs', verbose_name='UBSs que a notícia se relaciona: ')),
            ],
        ),
    ]
