# Generated by Django 4.2.2 on 2023-10-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubs', '0011_alter_noticias_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='data',
            field=models.DateField(null=True, verbose_name='Data da notícia ou do Informe: '),
        ),
    ]
