# Generated by Django 5.0 on 2023-12-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubs', '0014_alter_noticias_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Notícia de destaque?'),
        ),
    ]
