# Generated by Django 4.2.2 on 2023-08-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Vacina')),
                ('campanha', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Campanha da Vacina')),
                ('lote', models.CharField(max_length=30, verbose_name='Lote da Vacina')),
                ('data_de_vencimento', models.DateTimeField(verbose_name='Data de Vencimento')),
                ('observacao', models.CharField(blank=True, default=None, max_length=400, null=True, verbose_name='Observação sobre a Vacina: ')),
                ('disponibilidade', models.CharField(max_length=400, verbose_name='Postos em que a Vacina está disponível: ')),
            ],
        ),
    ]
