# Generated by Django 4.2.2 on 2023-09-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacinas',
            name='disponivel',
            field=models.BooleanField(default=False, verbose_name='Está disponível? '),
        ),
    ]
