# Generated by Django 5.0 on 2023-12-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0004_remove_vacinas_campanha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacinas',
            name='disponivel',
        ),
    ]
