# Generated by Django 5.0 on 2023-12-08 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubs', '0015_noticias_destaque'),
        ('vacinas', '0005_remove_vacinas_disponivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidade', models.BooleanField(default=False, verbose_name='Está disponível?')),
                ('data', models.ManyToManyField(blank=True, default=None, null=True, to='ubs.diasemana', verbose_name='Em qual/quais dia(s), a vacina está disponível?')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacinas.vacinas')),
            ],
        ),
    ]
