# Generated by Django 4.2.2 on 2023-10-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes_sus_vacinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaosus',
            name='cartaoSus',
            field=models.ImageField(null=True, upload_to='cartao_sus', verbose_name='Cópia do Cartão do Sus '),
        ),
    ]
