# Generated by Django 4.2.2 on 2023-12-19 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartoes_sus_vacinas', '0004_alter_cartaosus_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaosus',
            name='users',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
